import{a as p,S as m,i as l}from"./assets/vendor-BBPOLzfb.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const g="49423998-53f799fc922e58b577969e777",h="https://pixabay.com/api/";async function y(o){try{return(await p.get(h,{params:{key:g,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data.hits}catch(r){throw console.error("Error fetching images:",r),r}}let c=null;function b(o,r){console.log("Images to render:",o);const i=o.map(({webformatURL:s,largeImageURL:e,tags:t,likes:a,views:u,comments:f,downloads:d})=>`
        <div class="photo-card">
            <a href="${e}" class="gallery-link">
                <img src="${s}" alt="${t}" loading="lazy" />
            </a>
            <div class="info">
                <p class="info-item"><b>Likes</b><span>${a}</span></p>
                <p class="info-item"><b>Views</b><span>${u}</span></p>
                <p class="info-item"><b>Comments</b><span>${f}</span></p>
                <p class="info-item"><b>Downloads</b><span>${d}</span></p>
            </div>
        </div>
    `).join("");r.insertAdjacentHTML("beforeend",i),c?(c.refresh(),console.log("🔄 Lightbox оновлено!")):(c=new m(".gallery a",{captionsData:"alt",captionDelay:250}),console.log("✅ Lightbox ініціалізований!"))}const n={form:document.querySelector(".search-form"),input:document.querySelector("#search-text"),button:document.querySelector('button[type="submit"]'),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};function L(){n.loader.classList.remove("hidden")}function v(){n.loader.classList.add("hidden")}function w(){n.gallery.innerHTML=""}n.form?n.form.addEventListener("submit",async o=>{o.preventDefault();const r=n.input.value.trim();if(!r.length){l.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}w(),L();try{const s=(await y(r)).hits;!s||s.length===0?l.info({title:"No Results",message:"No images found for your search.",position:"topRight"}):b(s,n.gallery)}catch{l.error({title:"Error",message:"Something went wrong. Please try again.",position:"topRight"})}finally{v()}o.target.reset()}):console.error("⚠️ Форма не знайдена в DOM!");
//# sourceMappingURL=index.js.map
